void#testInvalidTestCase#(#)#{#TestRunner#runner#=#createRunner#(#InvalidTestCase#.#class#)#;#runner#.#run#(#)#;##// On junit3 this is a FAILURE, on junit4 this is an ERROR#int#ret#=#runner#.#getRetCode#(#)#;##if#(#ret#!=#JUnitTestRunner#.#FAILURES#&&#ret#!=#JUnitTestRunner#.#ERRORS#)#{#fail#(#"Unexpected result "#+#ret#+#" from junit runner"#)#;#}##// JUNIT3 test##//assertEquals(error, JUnitTestRunner.FAILURES, runner.getRetCode());##//@fixme as of now does not report the original stacktrace.##//assertTrue(error, error.indexOf("thrown on purpose") != -1);#}