void#endTest#(#Test#test#)#{##// Fix for bug #5637 - if a junit.extensions.TestSetup is##// used and throws an exception during setUp then startTest##// would never have been called##if#(#!#testStarts#.#containsKey#(#test#)#)#{#startTest#(#test#)#;#}##Element#currentTest#=#null#;##if#(#!#failedTests#.#containsKey#(#test#)#)#{#currentTest#=#doc#.#createElement#(#TESTCASE#)#;#String#n#=#JUnitVersionHelper#.#getTestCaseName#(#test#)#;#currentTest#.#setAttribute#(#ATTR_NAME#,#n#==#null#?#UNKNOWN#:#n#)#;##// a TestSuite can contain Tests from multiple classes,##// even tests with the same name - disambiguate them.#currentTest#.#setAttribute#(#ATTR_CLASSNAME#,#JUnitVersionHelper#.#getTestCaseClassName#(#test#)#)#;#rootElement#.#appendChild#(#currentTest#)#;#testElements#.#put#(#test#,#currentTest#)#;#}#else#{#currentTest#=#(#Element#)#testElements#.#get#(#test#)#;#}##Long#l#=#(#Long#)#testStarts#.#get#(#test#)#;#currentTest#.#setAttribute#(#ATTR_TIME#,#""#+#(#(#System#.#currentTimeMillis#(#)#-#l#.#longValue#(#)#)#/#ONE_SECOND#)#)#;#}